-- Seed courses with track/area/workload data
insert into public.courses (slug, name, price_cents, active, track, area, workload_hours, modality, duration_months_min, duration_months_max, tcc_required)
values
  ('acupuntura', 'Técnico em Acupuntura', 259000, false, 'regular', 'saude', null, 'EAD', 6, 12, true),
  ('administracao', 'Técnico em Administração', 219000, true, 'regular', 'administracao', 1340, 'EAD', 6, 12, true),
  ('agente-comunitario-de-saude', 'Técnico em Agente Comunitário de Saúde', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('agricultura', 'Técnico em Agricultura', 139000, true, 'competencia_profissional', 'meio-ambiente', null, 'EAD', 6, 12, true),
  ('agrimensura', 'Técnico em Agrimensura', 139000, true, 'competencia_profissional', 'construcao', null, 'EAD', 6, 12, true),
  ('agropecuaria', 'Técnico em Agropecuária', 139000, false, 'competencia_profissional', 'meio-ambiente', null, 'EAD', 6, 12, true),
  ('analises-clinicas', 'Técnico em Análises Clínicas', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('atendimento-e-vendas', 'Técnico em Atendimento e Vendas', 219000, true, 'regular', 'administracao', 1320, 'EAD', 6, 12, true),
  ('automacao-industrial', 'Técnico em Automação Industrial', 249000, true, 'regular', 'engenharia', 1590, 'EAD', 6, 12, true),
  ('banco-de-dados', 'Técnico em Banco de Dados', 239000, true, 'regular', 'tecnologia', null, 'EAD', 6, 12, true),
  ('biotecnologia', 'Técnico em Biotecnologia', 139000, true, 'competencia_profissional', 'tecnologia', null, 'EAD', 6, 12, true),
  ('comercio-exterior', 'Técnico em Comércio Exterior', 219000, true, 'regular', 'administracao', null, 'EAD', 6, 12, true),
  ('compliance', 'Técnico em Compliance', 219000, true, 'regular', 'administracao', null, 'EAD', 6, 12, true),
  ('computacao-grafica', 'Técnico em Computação Gráfica', 239000, true, 'regular', 'tecnologia', 1200, 'EAD', 6, 12, true),
  ('contabilidade', 'Técnico em Contabilidade', 219000, true, 'regular', 'administracao', 1100, 'EAD', 6, 12, true),
  ('controle-de-obras', 'Técnico em Controle de Obras', 239000, true, 'regular', 'construcao', null, 'EAD', 6, 12, true),
  ('cuidador-de-idosos', 'Técnico em Cuidador de Idosos', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('defesa-civil', 'Técnico em Defesa Civil', 139000, true, 'competencia_profissional', 'construcao', null, 'EAD', 6, 12, true),
  ('desenho-de-construcao-civil', 'Técnico em Desenho de Construção Civil', 239000, true, 'regular', 'construcao', null, 'EAD', 6, 12, true),
  ('desenvolvimento-de-sistemas', 'Técnico em Desenvolvimento de Sistemas', 239000, true, 'regular', 'tecnologia', 1280, 'EAD', 6, 12, true),
  ('design-grafico', 'Técnico em Design Gráfico', 139000, true, 'competencia_profissional', 'tecnologia', null, 'EAD', 6, 12, true),
  ('designer-de-interiores', 'Técnico em Designer de Interiores', 129000, true, 'competencia_profissional', 'servicos', null, 'EAD', 6, 12, true),
  ('edificacoes', 'Técnico em Edificações', 239000, true, 'regular', 'construcao', 1440, 'EAD', 6, 12, true),
  ('eletroeletronica', 'Técnico em Eletroeletrônica', 249000, true, 'regular', 'engenharia', 1440, 'EAD', 6, 12, true),
  ('eletromecanica', 'Técnico em Eletromecânica', 149000, true, 'competencia_profissional', 'engenharia', null, 'EAD', 6, 12, true),
  ('eletronica', 'Técnico em Eletrônica', 249000, true, 'regular', 'engenharia', 1450, 'EAD', 6, 12, true),
  ('eletrotecnica', 'Técnico em Eletrotécnica', 249000, true, 'regular', 'engenharia', 1340, 'EAD', 6, 12, true),
  ('empreendedorismo', 'Técnico em Empreendedorismo', 219000, true, 'regular', 'administracao', null, 'EAD', 6, 12, true),
  ('enfermagem', 'Técnico em Enfermagem', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('equipamentos-biomedicos', 'Técnico em Equipamentos Biomédicos', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('estetica', 'Técnico em Estética', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('estetica-e-cosmetologia', 'Técnico em Estética e Cosmetologia', 259000, true, 'regular', 'saude', 1440, 'EAD', 6, 12, true),
  ('eventos', 'Técnico em Eventos', 129000, true, 'competencia_profissional', 'administracao', null, 'EAD', 6, 12, true),
  ('farmacia', 'Técnico em Farmácia', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('financas', 'Técnico em Finanças', 129000, true, 'competencia_profissional', 'administracao', null, 'EAD', 6, 12, true),
  ('gastronomia', 'Técnico em Gastronomia', 129000, true, 'competencia_profissional', 'servicos', null, 'EAD', 6, 12, true),
  ('geoprocessamento', 'Técnico em Geoprocessamento', 239000, false, 'regular', 'construcao', null, 'EAD', 6, 12, true),
  ('gerencia-em-saude', 'Técnico em Gerência em Saúde', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('gestao-de-qualidade', 'Técnico em Gestão de Qualidade', 219000, true, 'regular', 'administracao', null, 'EAD', 6, 12, true),
  ('guia-de-turismo', 'Técnico em Guia de Turismo', 219000, true, 'regular', 'servicos', 1200, 'EAD', 6, 12, true),
  ('informatica', 'Técnico em Informática', 239000, true, 'regular', 'tecnologia', 1440, 'EAD', 6, 12, true),
  ('informatica-para-internet', 'Técnico em Informática para Internet', 239000, true, 'regular', 'tecnologia', 1440, 'EAD', 6, 12, true),
  ('instrumentacao', 'Técnico em Instrumentação', 249000, true, 'regular', 'engenharia', null, 'EAD', 6, 12, true),
  ('logistica', 'Técnico em Logística', 219000, true, 'regular', 'administracao', 1340, 'EAD', 6, 12, true),
  ('manutencao-de-aeronaves', 'Técnico em Manutenção de Aeronaves', 249000, true, 'regular', 'engenharia', null, 'EAD', 6, 12, true),
  ('manutencao-de-computadores', 'Técnico em Manutenção de Computadores', 239000, true, 'regular', 'tecnologia', null, 'EAD', 6, 12, true),
  ('manutencao-de-maquinas-industriais', 'Técnico em Manutenção de Máquinas Industriais', 149000, true, 'competencia_profissional', 'engenharia', null, 'EAD', 6, 12, true),
  ('manutencao-de-maquinas-navais', 'Técnico em Manutenção de Máquinas Navais', 149000, true, 'competencia_profissional', 'engenharia', null, 'EAD', 6, 12, true),
  ('manutencao-e-suporte-para-informatica', 'Técnico em Manutenção e Suporte para Informática', 239000, true, 'regular', 'tecnologia', null, 'EAD', 6, 12, true),
  ('manutencao-industrial', 'Técnico em Manutenção Industrial', 249000, true, 'regular', 'engenharia', null, 'EAD', 6, 12, true),
  ('maquinas-pesadas', 'Técnico em Máquinas Pesadas', 149000, true, 'competencia_profissional', 'engenharia', null, 'EAD', 6, 12, true),
  ('marketing', 'Técnico em Marketing', 129000, true, 'competencia_profissional', 'administracao', null, 'EAD', 6, 12, true),
  ('marketing-e-comunicacao', 'Técnico em Marketing e Comunicação', 219000, true, 'regular', 'administracao', 1340, 'EAD', 6, 12, true),
  ('massoterapia', 'Técnico em Massoterapia', 259000, false, 'regular', 'saude', null, 'EAD', 6, 12, true),
  ('mecanica', 'Técnico em Mecânica', 249000, true, 'regular', 'engenharia', null, 'EAD', 6, 12, true),
  ('mecanica-industrial', 'Técnico em Mecânica Industrial', 249000, true, 'regular', 'engenharia', 1560, 'EAD', 6, 12, true),
  ('mecatronica', 'Técnico em Mecatrônica', 249000, true, 'regular', 'engenharia', null, 'EAD', 6, 12, true),
  ('meio-ambiente', 'Técnico em Meio Ambiente', 229000, true, 'regular', 'meio-ambiente', 1380, 'EAD', 6, 12, true),
  ('metalurgia', 'Técnico em Metalurgia', 149000, true, 'competencia_profissional', 'engenharia', null, 'EAD', 6, 12, true),
  ('mineracao', 'Técnico em Mineração', 239000, true, 'regular', 'construcao', null, 'EAD', 6, 12, true),
  ('nutricao', 'Técnico em Nutrição', 259000, true, 'regular', 'saude', 1580, 'EAD', 6, 12, true),
  ('nutricao-e-dietetica', 'Técnico em Nutrição e Dietética', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('optica', 'Técnico em Óptica', 129000, true, 'competencia_profissional', 'servicos', null, 'EAD', 6, 12, true),
  ('papel-e-celulose', 'Técnico em Papel e Celulose', 149000, true, 'competencia_profissional', 'engenharia', null, 'EAD', 6, 12, true),
  ('petroquimica', 'Técnico em Petroquímica', 249000, false, 'regular', 'engenharia', null, 'EAD', 6, 12, true),
  ('podologia', 'Técnico em Podologia', 259000, false, 'regular', 'saude', null, 'EAD', 6, 12, true),
  ('prevencao-e-combate-ao-incendio', 'Técnico em Prevenção e Combate ao Incêndio', 139000, true, 'competencia_profissional', 'construcao', null, 'EAD', 6, 12, true),
  ('processos-gerenciais', 'Técnico em Processos Gerenciais', 219000, true, 'regular', 'administracao', null, 'EAD', 6, 12, true),
  ('programacao-de-jogos-digitais', 'Técnico em Programação de Jogos Digitais', 239000, true, 'regular', 'tecnologia', 1440, 'EAD', 6, 12, true),
  ('protese-dentaria', 'Técnico em Prótese Dentária', 259000, false, 'regular', 'saude', null, 'EAD', 6, 12, true),
  ('qualidade', 'Técnico em Qualidade', 129000, true, 'competencia_profissional', 'administracao', null, 'EAD', 6, 12, true),
  ('quimica', 'Técnico em Química', 129000, true, 'competencia_profissional', 'servicos', null, 'EAD', 6, 12, true),
  ('radiologia', 'Técnico em Radiologia', 159000, false, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('recursos-humanos', 'Técnico em Recursos Humanos', 219000, true, 'regular', 'administracao', 1250, 'EAD', 6, 12, true),
  ('redes-de-computadores', 'Técnico em Redes de Computadores', 239000, true, 'regular', 'tecnologia', 1200, 'EAD', 6, 12, true),
  ('refrigeracao-e-climatizacao', 'Técnico em Refrigeração Climatização', 149000, true, 'competencia_profissional', 'engenharia', null, 'EAD', 6, 12, true),
  ('robotica', 'Técnico em Robótica', 239000, false, 'regular', 'tecnologia', null, 'EAD', 6, 12, true),
  ('saude-bucal', 'Técnico em Saúde Bucal', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, true),
  ('secretaria-escolar', 'Técnico em Secretaria Escolar', 219000, true, 'regular', 'administracao', 1200, 'EAD', 6, 12, true),
  ('secretariado', 'Técnico em Secretariado', 219000, true, 'regular', 'administracao', null, 'EAD', 6, 12, true),
  ('seguranca-da-informacao', 'Técnico em Segurança da Informação', 239000, true, 'regular', 'tecnologia', null, 'EAD', 6, 12, true),
  ('seguranca-do-trabalho', 'Técnico em Segurança do Trabalho', 219000, true, 'regular', 'administracao', 1560, 'EAD', 6, 12, true),
  ('servicos-juridicos', 'Técnico em Serviços Jurídicos', 129000, true, 'competencia_profissional', 'administracao', null, 'EAD', 6, 12, true),
  ('sistemas-de-energia-renovavel', 'Técnico em Sistemas de Energia Renovável', 139000, true, 'competencia_profissional', 'tecnologia', null, 'EAD', 6, 12, true),
  ('soldagem', 'Técnico em Soldagem', 149000, true, 'competencia_profissional', 'engenharia', null, 'EAD', 6, 12, true),
  ('suporte-em-ti', 'Técnico em Suporte em TI', 239000, true, 'regular', 'tecnologia', null, 'EAD', 6, 12, true),
  ('telecomunicacoes', 'Técnico em Telecomunicações', 239000, true, 'regular', 'tecnologia', null, 'EAD', 6, 12, true),
  ('teologia', 'Técnico em Teologia', 219000, false, 'regular', 'servicos', null, 'EAD', 6, 12, true),
  ('topografia', 'Técnico em Topografia', 239000, true, 'regular', 'construcao', null, 'EAD', 6, 12, true),
  ('traducao-e-interpretacao-de-libras', 'Técnico em Tradução e Interpretação de Libras', 139000, true, 'competencia_profissional', 'tecnologia', null, 'EAD', 6, 12, true),
  ('transacoes-imobiliarias', 'Técnico em Transações Imobiliárias', 219000, true, 'regular', 'administracao', 1300, 'EAD', 6, 12, true),
  ('transito', 'Técnico em Trânsito', 139000, true, 'competencia_profissional', 'construcao', null, 'EAD', 6, 12, true),
  ('turismo', 'Técnico em Turismo', 219000, true, 'regular', 'servicos', null, 'EAD', 6, 12, true),
  ('vendas', 'Técnico em Vendas', 129000, true, 'competencia_profissional', 'administracao', null, 'EAD', 6, 12, true),
  ('veterinaria', 'Técnico em Veterinária', 159000, true, 'competencia_profissional', 'saude', null, 'EAD', 6, 12, false)
on conflict (slug) do update set
  name = excluded.name,
  price_cents = excluded.price_cents,
  active = excluded.active,
  track = excluded.track,
  area = excluded.area,
  workload_hours = excluded.workload_hours,
  modality = excluded.modality,
  duration_months_min = excluded.duration_months_min,
  duration_months_max = excluded.duration_months_max,
  tcc_required = excluded.tcc_required;